name: Build Application

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onedir --windowed --name=secan src/main.py

    - name: Create Windows Installer
      if: ${{ matrix.os }} == 'windows-latest'
      run: |
        choco install nsis -y

        cat > installer.nsi << 'EOF'
        !define APP_NAME "Secan"
        !define APP_VERSION "1.0.0"
        !define APP_PUBLISHER "Your Company"
        !define APP_EXE "secan.exe"
        
        Name "${APP_NAME}"
        OutFile "secan-installer.exe"
        InstallDir "$PROGRAMFILES\${APP_NAME}"
        
        Page directory
        Page instfiles
        
        Section "Install"
          SetOutPath "$INSTDIR"
          File /r "dist\secan\*"
          
          # Create desktop shortcut
          CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}"
          
          # Create start menu shortcut
          CreateDirectory "$SMPROGRAMS\${APP_NAME}"
          CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}"
          CreateShortCut "$SMPROGRAMS\${APP_NAME}\Uninstall.lnk" "$INSTDIR\uninstaller.exe"
          
          # Create uninstaller
          WriteUninstaller "$INSTDIR\uninstaller.exe"
          
          # Registry entries for Add/Remove Programs
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "DisplayName" "${APP_NAME}"
          WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}" "UninstallString" "$INSTDIR\uninstaller.exe"
        SectionEnd
        
        Section "Uninstall"
          Delete "$INSTDIR\*.*"
          RMDir /r "$INSTDIR"
          Delete "$DESKTOP\${APP_NAME}.lnk"
          RMDir /r "$SMPROGRAMS\${APP_NAME}"
          DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"
        SectionEnd
        EOF
        
        # Build installer
        makensis installer.nsi
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: dist/