name: Build Application

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onedir --windowed --name=secan src/main.py

    - name: Create Windows Installer
      if: matrix.os == 'windows-latest'
      run: |
        chmod +x build/windows_installer.ps1
        powershell -ExecutionPolicy Bypass -File build/windows_installer.ps1
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: dist/